# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kolekcjonerMonet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kolekcjonerMonet
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

end
